language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer install --dev
  - phpenv rehash

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-text --coverage-clover=coverage.clover
