language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer install --dev
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-text --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
